export const todos = [
    {
      id: 1,
      heading: "Heading 1",
      text: "Learn React",
      completed: false,
    },
    {
      id: 2,
      heading: "Heading 2",
      text: "Learn Flask",
      completed: false,
    },
    {
      id: 3,
      heading: "Heading 3",
      text: "Learn Tailwind CSS",
      completed: false,
    },
    // {
    //   id: 4,
    //   heading: "Heading 4",
    //   text: "Learn TanStack Query",
    //   completed: false,
    // },
    // {
    //   id: 5,
    //   heading: "Heading 5",
    //   text: "Build a To-Do App",
    //   completed: false,
    // },
    // {
    //   id: 6,
    //   heading: "Heading 6",
    //   text: "Deploy the App",
    //   completed: false,
    // },
    // {
    //   id: 7,
    //   heading: "Heading 7",
    //   text: "Learn about Databases",
    //   completed: false,
    // },
    // {
    //   id: 8,
    //   heading: "Heading 8",
    //   text: "Practice with More Projects",
    //   completed: false,
    // },
    // {
    //   id: 9,
    //   heading: "Heading 9",
    //   text: "Explore Advanced Concepts",
    //   completed: false,
    // },
    // {
    //   id: 10,
    //   heading: "Heading 10",
    //   text: "Contribute to Open Source",
    //   completed: false,
    // },
    // {
    //   id: 11,
    //   heading: "Heading 11",
    //   text: "Network with Other Developers",
    //   completed: false,
    // },
    // {
    //   id: 12,
    //   heading: "Heading 12",
    //   text: "Stay Up-to-Date with Trends",
    //   completed: false,
    // },
    // {
    //   id: 13,
    //   heading: "Heading 13",
    //   text: "Build a Portfolio",
    //   completed: false,
    // },
    // {
    //   id: 14,
    //   heading: "Heading 14",
    //   text: "Build a network with Other Developers",
    //   completed: false,
    // },
    // {
    //   id: 15,
    //   heading: "Heading 15",
    //   text: "Land Your Dream Role",
    //   completed: false,
    // },
    // {
    //   id: 16,
    //   heading: "Heading 16",
    //   text: "Enjoy the Journey!",
    //   completed: false,
    // },
  ];